# stemdlConfig.yaml

# SciML-Bench
# Copyright © 2021 Scientific Machine Learning Research Group
# Scientific Computing Department, Rutherford Appleton Laboratory
# Science and Technology Facilities Council, UK.
# All rights reserved.

# This is a configuration file for the Stemdl classification benchmark.

# Training dir
train_dir: ~/sciml_bench/datasets/stemdl_ds1/training

# Test dir
test_dir: ~/sciml_bench/datasets/stemdl_ds1/testing

# Validation dir
val_dir: ~/sciml_bench/datasets/stemdl_ds1/validation

# Inference dir
inference_dir: ~/sciml_bench/datasets/stemdl_ds1/inference

# Log file for recording runtimes
log_file: ./stemdlLog

# Log file for MLCommons logging
mlperf_logfile: ./mlperf_stemdl.log

#? Model file
model_file : ./stemdlModel.h5

# Hyperparameters
seed: 1234

learning_rate: 0.001

epochs: 1

batchsize: 32

train_split: 0.8

resnet: resnet18

nodes: 1

gpu: 2


